### ISSUE TITLE
Rules in kube-apiserver.rules are taking too long for Prometheus to evaluate them

### ISSUE THREAD

**Issue by Annegies** [kubernetes-monitoring/kubernetes-mixin#413] opened 2020-04-30 11:15 UTC
Hi,

We're running EKS clusters with the prometheus-operator helm chart, since yesterday we're running the version including the kube-apiserver.rules. 

We noticed that a few rules sometimes take too long and exceeds our set srape_interval (30s).
The primary cause is 'apiserver_request:availability30d'.
For now we've disabled the rule group but i was was wondering if others were experiencing this also and what could be done to make this work

**Comment by brancz** [comment] 2020-05-05 14:01
You're not the only one. The right solution to this is still being worked out (RE https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/411).

**Comment by timatooth** [comment] 2020-05-06 01:23
Had to remove these rules too as they were causing so much flap for us after reaching about 17GB of metrics which is ~15 days worth. Currently using the latest prometheus-operator chart.

Load graph for dramatic effect:
![Screen Shot 2020-05-06 at 11 13 59 am](https://user-images.githubusercontent.com/980629/81130567-94544c00-8f8b-11ea-8f76-ff9384c0b8ce.png)

**Comment by metalmatze** [comment] 2020-06-29 16:07
Closing as a duplicate of #411. I'm still trying to figure out a proper solution for this...

**Closed by metalmatze** 2020-06-29 16:07 UTC
